"""create employees and work schedules

Revision ID: d5775ba95e23
Revises: b7e050e6a1e9
Create Date: 2026-08-09 01:44:33.467769

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5775ba95e23"
down_revision: str | Sequence[str] | None = "b7e050e6a1e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("personnel_number", sa.String(length=50), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_employees_team_id_teams"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        sa.UniqueConstraint("email", name=op.f("uq_employees_email")),
        sa.UniqueConstraint("personnel_number", name=op.f("uq_employees_personnel_number")),
    )
    op.create_index(op.f("ix_employees_team_id"), "employees", ["team_id"], unique=False)
    op.create_table(
        "employee_work_schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("planned_hours", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.CheckConstraint(
            "planned_hours >= 0 AND planned_hours <= 24",
            name=op.f("ck_employee_work_schedules_planned_hours_range"),
        ),
        sa.CheckConstraint(
            "weekday >= 0 AND weekday <= 6", name=op.f("ck_employee_work_schedules_weekday_range")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_work_schedules_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_work_schedules")),
        sa.UniqueConstraint(
            "employee_id", "weekday", name=op.f("uq_employee_work_schedules_employee_id")
        ),
    )
    op.create_index(
        op.f("ix_employee_work_schedules_employee_id"),
        "employee_work_schedules",
        ["employee_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_employee_work_schedules_employee_id"), table_name="employee_work_schedules"
    )
    op.drop_table("employee_work_schedules")
    op.drop_index(op.f("ix_employees_team_id"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
